### ISSUE TITLE
Direction of ownership-or-control relationships for rr records is incorrect

### ISSUE THREAD

**Issue by kd-ods** [openownership/bodspipelines#10]
The GLEIF [Relationship Record (RR) CDF Format docs](https://www.gleif.org/about-lei/common-data-file-format/current-versions/level-2-data-relationship-record-rr-cdf-2-1-format/2023-03-07_state-transition-validation-rules_v2.7.1_final.pdf) specify that the start node in a record is the child or lower node, and the end node is the parent node. 

In BODS terms, this means that the start node is the `subject` of an ooc statement and the end node is the `interestedParty`. However, we currently have this [the wrong way around](https://github.com/openownership/bodspipelines/blob/0668343894e8779c489443757c6fa2ec622f715c/bodspipelines/pipelines/gleif/transforms.py#L95). 

(I think it's only in rr records that this is happening. Worth checking, though.)

**Evidence of the problem:**
Looking at a particular example. Under the parents section here (https://search.gleif.org/#/record/5493005S591LT1RDBJ14) you can see that AEGON Investment Management B.V. (LEI code 5493005S591LT1RDBJ14) has a single entity (AEGON N.V.) recorded as its direct parent and its ultimate parent. 

Looking at the BODS GLEIF data, we would expect that there would be one or two ownership-or-control statements which have the AEGON Investment Management B.V. entity statement (BODS statementID 9310e3ea-c6e6-1bd9-def1-cc5e902785da) as the subject. (One if we have consolidated the two interests - direct and ultimate parent - into a single ooc statement. Two, otherwise.) However there are 153 such statements. See this by running on Datasette at https://bods-data-datasette.openownership.org/gleif:

```
select interestedparty_describedbyentitystatement from ooc_statement
where subject_describedbyentitystatement='9310e3ea-c6e6-1bd9-def1-cc5e902785da'
```

Sure enough, if I assume we have the mapping of subject <--> interested parties the wrong way around and run:

```
select subject_describedbyentitystatement from ooc_statement
where interestedparty_describedbyentitystatement='9310e3ea-c6e6-1bd9-def1-cc5e902785da'
```

... there are two identical results:

c0ae9cb2-fb7c-1b72-70c4-d4c950aa954b
c0ae9cb2-fb7c-1b72-70c4-d4c950aa954b

And c0ae9cb2-fb7c-1b72-70c4-d4c950aa954b is the entity statement for AEGON N.V. 

_(Thanks to our colleagues at GLEIF for spotting this.)_

**Comment by radix0000** [comment]
The code has been tweaked and the pipeline rerun. Please check results and commit if this issue can closed.

**Comment by kd-ods** [comment]
I've re-run those queries on the [newly published 2023-04-12 data](https://bods-data-datasette.openownership.org/gleif) and everything now looks as expected. 

Thanks @radix0000!

**Comment by StephenAbbott** [comment]
Brilliant work @kd-ods and @radix0000!
