### ISSUE TITLE
Handle more relationship information

### ISSUE THREAD

**Issue by kd-ods** [openownership/bodspipelines#13]
As of June 2023, there are [relationship CDF fields](https://www.gleif.org/en/about-lei/common-data-file-format/current-versions/level-2-data-relationship-record-rr-cdf-2-1-format) that are [not mapped](https://github.com/openownership/bodspipelines/blob/0668343894e8779c489443757c6fa2ec622f715c/bodspipelines/pipelines/gleif/transforms.py#L95) to BODS 0.2. The following mappings could (and should?) be added:

- RelationshipType -> Interest.Details
- RegistrationStatus -> 
  - Annotations.[0].statementPointerTarget="/";
  - Annotations.[0].motivation= "commenting";
  - Annotations.[0].description = "GLEIF registration status: [RegistrationStatus]"; 

The following can be left unmapped:

- RelationshipStatus

- RelationshipQualifiers

- RelationshipQuantifiers

- RelationshipPeriods.RelationshipPeriod.PeriodType=="ACCOUNTING_PERIOD"

- RelationshipPeriods.RelationshipPeriod.PeriodType=="DOCUMENT_FILING_PERIOD"

**Comment by kathryn-ods** [comment]
These have been added now
