### ISSUE TITLE
GLEIF transforms.py: use BODS interest.details field to store RelationshipType and ExceptionCategory

### ISSUE THREAD

**Issue by kd-ods** [openownership/bodspipelines#15]
### Description of issue

At the moment we don't store RelationshipType and ExceptionCategory values from the GLEIF XML in BODS ([see transforms.py](https://github.com/openownership/bodspipelines/blob/main/bodspipelines/pipelines/gleif/transforms.py)). This [GLEIF information](https://www.gleif.org/en/about-lei/common-data-file-format/current-versions/level-2-data-relationship-record-rr-cdf-2-1-format#) about the interests between entities shouldn't be lost. 

This will also help when/if an exception is later replaced with a relationship.

### Suggested resolution

We should store the RelationshipType value under `interest.details` as sthg like 'LEI RelationshipType: <value>'. (And we should store XML ExceptionCategory value in the OOC `interest.details` field as 'LEI Exception Category: <value>')

**Comment by radix0000** [comment]
For the reporting exceptions the `interest.details` field is currently already being used e.g.

```
    "interests": [
      {
        "type": "other-influence-or-control",
        "interestLevel": "direct",
        "beneficialOwnershipOrControl": false,
        "details": "A controlling interest."
      }
```

**Comment by kd-ods** [comment]
'A controlling interest' is not very semantically helpful, so we can replace it with ExceptionCategory where we have one.

**Comment by kathryn-ods** [comment]
This has been implemented
