### ISSUE TITLE
Annotate Important Information In BODS Statements

### ISSUE THREAD

**Issue by radix0000** [openownership/bodspipelines#17]
Manual checking of BODS output statements has raised the issue that certain information useful for this task is not contained within individual statements. For instance an Ownership or Control statement will simply reference the statementIDs of linked statements, making it an onerous task of following those links in order to understand what source data caused the OOC statement to be created. It may be useful to include more data (e.g. LEIs in the case of GLEIF) in annotations to make such manual checking easier.

**Comment by kathryn-ods** [comment]
Annotations have been used to resolve this
