### ISSUE TITLE
Update publicationDetails for GLEIF > BODS pipeline

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/bodspipelines#18]
The GLEIF to BODS pipeline currently provides the following publication details for BODS statements:

- `publicationDetails_publisher_name` = OpenOwnership Register
- `publicationDetails_publisher_url` = [https://register.openownership.org/](https://register.openownership.org/)
- `publicationDetails_license` = https://register.openownership.org/terms-and-conditions

However this pipeline is not connected to the Open Ownership Register so we should change these to:

- `publicationDetails_publisher_name` = Open Ownership
- `publicationDetails_publisher_url` = [https://www.openownership.org/en/](https://www.openownership.org/)
- `publicationDetails_license` = https://creativecommons.org/publicdomain/zero/1.0/

**Comment by kathryn-ods** [comment]
this has been implemented
