### ISSUE TITLE
GLEIF - additional entity identifiers

### ISSUE THREAD

**Issue by lgs85** [openownership/bodspipelines#2]
We missed out from the original mappings that [LEI level 1 data](https://www.gleif.org/en/about-lei/common-data-file-format/current-versions/level-1-data-lei-cdf-3-1-format) has a `RegistrationAuthority` object. If possible, it would be good to add this where present to the BODS entity statement `identifiers` array. Specifically:

|LEI level 1 field|BODS entity statement field|
|-|-|
|`RegistrationAuthority/RegistrationAuthorityID`|`identifiers/1/scheme`|
|`RegistrationAuthority/RegistrationAuthorityEntityID`|`identifiers/1/id`|

using `/1/` here as shorthand to denote that this should be appended to the identifiers array and the LEI identifier kept. In reality there may be instances where there is just one of either identifier.

**Comment by kd-ods** [comment]
At the moment we only allow org-id scheme values in the `scheme` field. Could we please map `RegistrationAuthorityID` to `schemeName` instead? (See: https://standard.openownership.org/en/0.2.0/schema/reference.html#schema-identifier )

In the longer term it would be good to look at how the [LEI Registration Authorities list](https://www.gleif.org/en/about-lei/code-lists/gleif-registration-authorities-list) maps to org-id lists. There's a CSV on that page.

**Comment by radix0000** [comment]
Fixed
