### ISSUE TITLE
GLEIF - 'unknownInterest' not a feature of BODS v0.2

### ISSUE THREAD

**Issue by lgs85** [openownership/bodspipelines#4]
We are currently using 'unknownInterest' to represent unknown interest types, but this is a feature of BODS v0.3 rather than BODS v0.2. We should consider how to best represent this with BODS v0.2.

**Comment by kd-ods** [comment]
@lgs85 @radix0000 - Maybe we could use 'other-influence-or-control' and then [annotate](https://standard.openownership.org/en/0.2.0/schema/reference.html#annotation) this with the comment "The nature of this interest is unknown".

**Comment by radix0000** [comment]
Fixed
