### ISSUE TITLE
unrecognised escape characters

### ISSUE THREAD

**Issue by lgs85** [openownership/bodspipelines#5]
Attempting to check some (randomly selected) converted data with the BODS [data review tool](https://datareview.openownership.org) revealed an unrecognised escape character, which prevented the tool from working. Details:

`"statementID": "133a135c-28a4-5d73-2617-9965be7424a4"`
`"name": "ALEXANDERS\' PHARMACY LTD"`

removing the backslash and single quote from the name enables the tool to run

**Comment by radix0000** [comment]
So I am seeing this:

{"statementID": "133a135c-28a4-5d73-2617-9965be7424a4", "statementType": "entityStatement", "statementDate": "2019-02-23T07:01:16+00:00", "entityType": "registeredEntity", "name": "ALEXANDERS' PHARMACY LTD", "jurisdiction": "GB", "identifiers": [{"id": "2138006NAS74JWPZ2G43", "scheme": "XI-LEI", "schemeName": "Global Legal Entity Identifier Index"}], "addresses": [{"type": "registered", "address": "C/O DUNCAN SHEARD GLASS, 45 HOGHTON STREET, SOUTHPORT", "country": "GB", "postCode": "PR9 0PG"}, {"type": "business", "address": "27 MERRILOCKS ROAD, LIVERPOOL", "country": "GB", "postCode": "L23 6UL"}], "publicationDetails": {"publicationDate": "2023-03-12T20:51:31+00:00", "bodsVersion": "0.2", "license": "https://register.openownership.org/terms-and-conditions", "publisher": {"name": "OpenOwnership Register", "url": "https://register.openownership.org"}}, "source": {"type": ["officialRegister", "verified"], "description": "GLEIF"}}

on line 727 of bods-gleif-prod-alt6-1-2023-03-12-20-51-29-3d4562aa-ecb5-480b-a7a5-bb4ae234214d. Which on the face of it seems correct, as there shouldn't be any need to escape apostrophes in JSON. Are there any intermediate steps between downloading the data and putting it into the BODS data review tool that could have introduced that escape character?

**Comment by lgs85** [comment]
ah ok this is fine.

>Are there any intermediate steps between downloading the data and putting it into the BODS data review tool that could have introduced that escape character?

Yes, I did a bit of python wrangling then dumped it out as JSON, so suspect this is my fault. Apologies and thanks for checking.
