### ISSUE TITLE
"Duplicate" Records In GLEIF Data

### ISSUE THREAD

**Issue by radix0000** [openownership/bodspipelines#6]
There are about 346 LEI, 1239 RR and 438 REPEX records that don't make it through the pipeline because they are "duplicates" under current code.

For the 346 LEI record duplicates, 275 have one records whose RegistrationStatus is PENDING_ARCHIVAL and one with some other value such as ISSUED or LAPSED. Unfortunately there numerous other records with the PENDING_ARCHIVAL, so it is not an identifying criterion. There is one analogous case where the duplicate is a PENDING_TRANSFER record. 

There is one case where the RegistrationStatus for both is ISSUED, the LastUpdateDate is a few minutes apart and there are significant changes to the data.

There rest of the LEI duplicates (70) appear to be actual duplicates. The data is identical (including the LastUpdateDate) and they tend to occur sequentially.

In all cases it looks like taking the record with the newest LastUpdateDate is the best bet.

**Comment by radix0000** [comment]
Have come up with a possible solution to this "duplicates" issue, but it is rather complex and might make it harder to handle updates later. Some searching through the GLEIF website has come up with this alternative (Golden Copy) form of the data: https://www.gleif.org/en/lei-data/gleif-golden-copy/download-the-golden-copy which might not have duplicates, As a first step will test using this data, plus other fixes on an overnight run, and see how that works out tomorrow.

**Comment by StephenAbbott** [comment]
@radix0000 We have some contacts with the GLEIF team. Great to investigate using the Golden Copy - but want me to reach out to ask about the PENDING_ARCHIVAL/duplicates issues?

**Comment by radix0000** [comment]
@StephenAbbott This "Golden Copy" seems to have done the trick, ran overnight without finding any duplicates. Hopefully @lgs85 will have time to check over results some time today and we can finalise soon.

**Comment by radix0000** [comment]
Fixed
