### ISSUE TITLE
`incorporatedInJurisdiction` should be a JSON object

### ISSUE THREAD

**Issue by lgs85** [openownership/bodspipelines#7]
Apologies for not pointing this out before, but `incorporatedInJuridiction` should be a JSON object and not a string. See the [schema reference](https://standard.openownership.org/en/0.2.0/schema/reference.html#jurisdiction)

Note that `name` is mandatory - given that the GLEIF schema doesn't include a name, suggest using the country code to populate both the `name` and the `code` fields.

**Comment by lgs85** [comment]
@radix0000 i don't think this warrants a rerun of the whole pipeline, rather, can be done when we next run anyway

**Comment by radix0000** [comment]
Fixed
